cc_test(
    name = "heaps",
    srcs = ["test_heap.cpp"],
    deps = [
         "//exercise/heaps:event_scheduler",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++14"],
)
